/* Generated by autorevision - do not hand-hack! */

package unb.fga.calcnet;

public class autorevision {
    public static final String VCS_TYPE = "git";
    public static final String VCS_BASENAME = "CalcNet";
    public static final String VCS_UUID = "88b4eb81aed3ae20d73fb66d462366cb0fcc6408";
    public static final long VCS_NUM = 7;
    public static final String VCS_DATE = "2018-05-13T03:36:47Z";
    public static final String VCS_BRANCH = "master";
    public static final String VCS_TAG = "v0.1-rc0";
    public static final String VCS_TAG_OPENPGP = "";
    public static final long VCS_TICK = 0;
    public static final String VCS_EXTRA = "";

    public static final String VCS_ACTION_STAMP = "2018-05-13T03:36:47Z!lucas.engen.cc@gmail.com";
    public static final String VCS_FULL_HASH = "0fbe41e1bd0193afaa97d446ff33c2d65afe5bab";
    public static final String VCS_COMMIT_OPENPGP = "";
    public static final String VCS_SHORT_HASH = "0fbe41e";

    public static final boolean VCS_WC_MODIFIED = true;
}
