/* Generated by autorevision - do not hand-hack! */

namespace AutoRevision
{
    public class VersionInfo
    {
        public static string VcsType = "git";
        public static string VcsBasename = "CalcNet";
        public static string VcsUuid = "88b4eb81aed3ae20d73fb66d462366cb0fcc6408";
        public static string VcsNum = "26";
        public static string VcsDate = "2018-06-28T15:30:52Z";
        public static string VcsBranch = "2018-06-28T15:30:52Z";
        public static string VcsTag = "v0.1-rc3";
        public static string VcsTagOpenpgp = "";
        public static string VcsTick = "0";
        public static string VcsExtra = "";
        public static string VcsActionStamp = "2018-06-28T15:30:52Z!lucas.engen.cc@gmail.com";
        public static string VcsFullHash = "c9f23ff79fde80c3eaf5eb0f5509f86bbdd74a3f";
        public static string VcsCommitOpenpgp = "";
        public static string VcsShortHash = "c9f23ff";
        public static string VcsWcModified = "true";
    }
}
