/* Generated by autorevision - do not hand-hack! */

namespace AutoRevision
{
    public class VersionInfo
    {
        public static string VcsType = "git";
        public static string VcsBasename = "CalcNet";
        public static string VcsUuid = "88b4eb81aed3ae20d73fb66d462366cb0fcc6408";
        public static string VcsNum = "7";
        public static string VcsDate = "2018-05-13T03:36:47Z";
        public static string VcsBranch = "2018-05-13T03:36:47Z";
        public static string VcsTag = "v0.1-rc0";
        public static string VcsTagOpenpgp = "";
        public static string VcsTick = "0";
        public static string VcsExtra = "";
        public static string VcsActionStamp = "2018-05-13T03:36:47Z!lucas.engen.cc@gmail.com";
        public static string VcsFullHash = "0fbe41e1bd0193afaa97d446ff33c2d65afe5bab";
        public static string VcsCommitOpenpgp = "";
        public static string VcsShortHash = "0fbe41e";
        public static string VcsWcModified = "true";
    }
}
